class Empleado:
    def __init__(self):
        self.nombre = None
        self.apellido = None
        self.salario = 0
        self.proyectos_terminados = 0
        self.bono = 0
    def actualizar_salario(self):
        nuevo_salario = float(input("Nuevo Salario: "))
        self.salario = nuevo_salario
    def mostrar_informacion(self):
        print(f"{self.nombre} {self.apellido}...Salario: {self.salario}...Bono: {self.bono}...Proyects: {self.proyectos_terminados}")
    def calcular_bono(self):
        if self.proyectos_terminados >= 5:
            self.bono = round(self.salario * 0.10, 10)
        elif self.proyectos_terminados == 3 or self.proyectos_terminados == 5:
            self.bono = round(self.salario * 0.05, 10)
        else:
            self.bono = 0

#5 Test Cases with different circumstances, expected outputs are based on inputs that I chose to enter, generated by AI, customized by me.

# Test Case 1
empleado1 = Empleado("John", "Doe", 50000, 0, 0)
empleado1.actualizar_salario()
empleado1.proyectos_terminados = 6
empleado1.calcular_bono()
empleado1.mostrar_informacion()

# Expected Output 1
# John Doe...Salario: 100000...Bono: 10000...Proyectos: 6

# Test Case 2
empleado2 = Empleado("Alice", "Smith", 60000, 0, 3)
empleado2.actualizar_salario()
empleado2.proyectos_terminados = 3
empleado2.calcular_bono()
empleado2.mostrar_informacion()

# Expected Output 2
# Alice Smith...Salario: 10...Bono: 0.5...Proyectos: 3

# Test Case 3
empleado3 = Empleado("Bob", "Johnson", 55000, 0, 5)
empleado3.actualizar_salario()
empleado3.proyectos_terminados = 5
empleado3.calcular_bono()
empleado3.mostrar_informacion()

# Expected Output 3
# Bob Johnson...Salario: 100...Bono: 10...Proyectos: 5

# Test Case 4
empleado4 = Empleado("Eva", "Davis", 70000, 0, 2)
empleado4.actualizar_salario()
empleado4.proyectos_terminados = 2
empleado4.calcular_bono()
empleado4.mostrar_informacion()

# Expected Output 4
# Eva Davis...Salario: 53512...Bono: 0...Proyectos: 2

# Test Case 5
empleado5 = Empleado("Charlie", "Brown", 45000, 0, 8)
empleado5.actualizar_salario()
empleado5.proyectos_terminados = 8
empleado5.calcular_bono()
empleado5.mostrar_informacion()

# Expected Output 5
# Charlie Brown...Salario: 1289012...Bono: 128901.2...Proyectos: 8
